version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: movies
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  identity:
    image: identity-api:latest
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:6001      
    ports:
      - 6001:6001