@baseURL = http://localhost:5181

### Create a new movie
# @name createMovie
POST {{baseURL}}/api/movies
Content-Type: application/json
Accept: application/json

{
  "Title": "Inception 4",
  "Year": 2014,
  "Genre": [
    "Action",
    "Adventure",
    "Cinema",
    "Thriller"
  ]
}

### Save location information
@location = {{createMovie.response.headers.Location}}

### Get movie using location information
# @name getMovie
GET {{location}}
Content-Type: application/json
Accept: application/json

### Save the movie id
@movieId = {{getMovie.response.body.id}}

### Update a Movie using id
PUT {{baseURL}}/api/movies/{{movieId}}
Content-Type: application/json
Accept: application/json

{
  "Title": "Inception 55",
  "Year": 2011,
  "Genre": [
    "Kids",
    "Action"
  ]
}

### Get Movie using slug
Get {{baseURL}}/api/movies/inception-55-2011
Content-Type: application/json
Accept: application/json


### Get All Movies
GET {{baseURL}}/api/movies
Content-Type: application/json
Accept: application/json

### Delete a Movie using id
DELETE {{baseURL}}/api/movies/{{movieId}}
Content-Type: application/json
Accept: application/json
